#!/usr/bin/env python3
"""Turn the 10x20 console raster font into a C header.

Input is font-10x20.c/.h from https://github.com/idispatch/raster-fonts (the
same file apollo-ps3, apollo-ps4 and apollo-vita draw their text with), which
is ~180KB of commented C for 10KB of bitmap. Output is gui/src/font10x20.h,
holding only the 95 printable ASCII glyphs the GUI actually registers.

Each glyph is 20 rows of 2 bytes, 10 bits used and 6 padding, MSB leftmost.

    tools/make-font.py ~/github/apollo-ps3/include/font-10x20.h
"""
import re, sys, os

FIRST, LAST = 0x20, 0x7E

def main():
    src_path = sys.argv[1] if len(sys.argv) > 1 else "font-10x20.c"
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "gui", "src", "font10x20.h")
    text = open(src_path).read()

    # Match the byte pair AND the bit comment beside it, so the two have to
    # agree -- a parse that drifted would have to drift in both at once.
    rows = re.findall(r"0x([0-9A-Fa-f]{2}),\s*0x([0-9A-Fa-f]{2}),\s*/\*\s*([01]{10})\s*\*/", text)
    if len(rows) != 256 * 20:
        sys.exit("expected %d rows, parsed %d" % (256 * 20, len(rows)))
    data = bytearray()
    for hi, lo, bits in rows:
        v = (int(hi, 16) << 8) | int(lo, 16)
        if "".join("1" if (v >> (15 - i)) & 1 else "0" for i in range(10)) != bits:
            sys.exit("byte/bit mismatch at row %d" % (len(data) // 2))
        data += bytes((int(hi, 16), int(lo, 16)))

    keep = data[FIRST * 40:(LAST + 1) * 40]
    lines = []
    for i in range(0, len(keep), 10):
        lines.append("    " + " ".join("0x%02X," % b for b in keep[i:i + 10]))

    with open(out_path, "w") as f:
        f.write(
            "// Generated by tools/make-font.py -- do not edit.\n"
            "//\n"
            "// The 10x20 console font from https://github.com/idispatch/raster-fonts,\n"
            "// the one apollo-ps3, apollo-ps4 and apollo-vita draw with. Printable\n"
            "// ASCII only (0x%02X..0x%02X); the codes above it are CP437 box drawing,\n"
            "// which is not what Unicode 0x80..0xFF means, so registering them would\n"
            "// draw the wrong character rather than none.\n"
            "//\n"
            "// %d glyphs, 20 rows of 2 bytes each, 10 bits used per row, MSB leftmost.\n"
            "#pragma once\n\n"
            "#define FONT10X20_FIRST 0x%02X\n"
            "#define FONT10X20_LAST  0x%02X\n"
            "#define FONT10X20_W     10\n"
            "#define FONT10X20_H     20\n\n"
            "static const unsigned char kFont10x20[] = {\n%s\n};\n"
            % (FIRST, LAST, LAST - FIRST + 1, FIRST, LAST, "\n".join(lines)))
    print("%s: %d glyphs, %d bytes" % (out_path, LAST - FIRST + 1, len(keep)))

main()
